Added IDM user migration guide and SQL script
DEFRA/wildlife-licencing-team pull request #6
Opened 2024-02-05 10:55 UTC by richard-mohammed-def

2024-02-05 16:26 UTC, StuAA78 requested changes
Looks great, just a small requested tweak.

2024-02-05 16:26 UTC, StuAA78 commented on idm/readme.md
> +```
I can't make a suggested change due to the ` ``` ` but the comment's inside the backticks.

2024-02-05 17:49 UTC, richard-mohammed-def commented on idm/readme.md
> +```
not sure how I missed that lol

2024-04-22 10:15 UTC, StuAA78 approved these changes

2024-04-22 10:15 UTC, merged